[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]
dependsOn = ["setup"]

[phases.build]
cmds = ["pnpm --filter @oreli/prisma generate", "pnpm --filter @oreli/api build"]
dependsOn = ["install"]

[start]
cmd = "node apps/api/dist/main.js"
